### ISSUE TITLE
Provide example with Prismic

### ISSUE THREAD

**Issue by mathiasha** [axe312ger/gatsby-transformer-inline-svg#1]
It would be great if you could provide an example with Prismic as the CMS.
Or even better a generic one without any specific CMS in mind.

**Comment by mathiasha** [comment]
Actually reading your sourcecode it looks like you have Contentful specific code hardcoded in the plugin. Consider if you want to support other CMS's too.

**Comment by axe312ger** [comment]
I am not a prismic user, so its hard for me to find time to implement features which I won't need 😅 

But I am verry happy to accept an PR which adds prismic functionality :)
