### ISSUE TITLE
gatsby-source-filesystem support and v2

### ISSUE THREAD

**Issue by hazem3500** [axe312ger/gatsby-transformer-inline-svg#16]
Hey @axe312ger, 
I noticed that this plugin doesn't support `File` nodes so I tried making a pull request adding support for `gatsby-source-filesystem` but it turns out that the plugin is tied to `ContentfulAssets`.

So I've created another plugin [gatsby-transformer-inline-svg-v2](https://github.com/hazem3500/gatsby-transformer-inline-svg-v2) which supports `gatsby-source-filesystem` but it doesn't yet support caching, dataURI or passing SVGO options.

I was hoping if we could merge the two plugins and try to move the contentful specific parts into a plugin of its own since it would be better for a plugin with the name `gatsby-transformer-inline-svg` to be CMS agnostic, what do you think?

**Comment by axe312ger** [comment]
Yeah, sounds good to me! lets do this!

**Comment by axe312ger** [comment]
If we would set up an example that maybe renders svgs from Contentful and filesystem, we can have a CI running that checks every time the inlining works well

**Comment by hazem3500** [comment]
That's great, would like the plugin to support both contentful and the filesystem, or would you like the contentful part to be in its own plugin?

I'll be happy to send a PR soon adding file system support to this plugin

**Comment by axe312ger** [comment]
No, this plugin should just be able to work with filesystem and contentful

**Comment by axe312ger** [comment]
Released as v1.1.0 :)
