### ISSUE TITLE
Getting error related to originalContent

### ISSUE THREAD

**Issue by bobeagan** [axe312ger/gatsby-transformer-inline-svg#20]
When trying to reference the originalContent value, I receive a `String cannot represent value: <Buffer ...` error. Updating `fs.readFile()` to specify a `utf8` encoding fixes the issue for me.

```js
const svg = await fs.readFile(absolutePath, 'utf8')
```

According to https://nodejs.org/api/fs.html#fs_fs_readfile_path_options_callback
> If no encoding is specified, then the raw buffer is returned.

**Comment by bobeagan** [comment]
@axe312ger any chance to get this fix published to npm?

**Comment by iamkratos** [comment]
@axe312ger Please merge this fix with what's on npm

**Comment by iamkratos** [comment]
If anyone comes across this and is wondering how to maintain the plugin so that it doesn't update every time you un npm install, check this out: https://www.gatsbyjs.com/docs/loading-plugins-from-your-local-plugins-folder/#verifying-your-plugin-is-loading

**Comment by axe312ger** [comment]
published as v0.0.8
