### ISSUE TITLE
When is v1.0.0 going to be released to npm?

### ISSUE THREAD

**Issue by keyvanm** [axe312ger/gatsby-transformer-inline-svg#42]
Hi, thanks for your plugin! I was wondering when is v1.0.0 going to be published to npm? v0.1.0 which is the latest on npm has a dependency conflict with the latest version of `gatsby-source-contentful`

**Comment by axe312ger** [comment]
As soon somebody updates the plugin to be compatible with Gatsby.

I am very open to PRs

**Comment by axe312ger** [comment]
Sorry, looks like I simply forgot it. Published!
