### ISSUE TITLE
SVGs' ids conflict because of svgo plugin { cleanupIDs: true }

### ISSUE THREAD

**Issue by xMokAx** [axe312ger/gatsby-transformer-inline-svg#6]
I have many SVGs displayed on the same page and because of `svgo` plugin `{ cleanupIDs: true }`, all the ids are shortened to `a`, b  and because of `svgo` plugin `{ prefixIds: true }`, all the ids ended up the same like so: `id="prefix__a"`, `xlink:href="#prefix__a"` or `id="prefix__a"`, `clip-path="url(#prefix__a)"`. The result is that only the first SVG with the repeated id is displaying correctly and all the rest are broken.
A good solution for that is to disable `{ cleanupIDs: false}` or a much better solution is to allow the user to pass his own `svgo` configuration.

**Comment by axe312ger** [comment]
Sounds good 👍 

Pull requests welcome :)

**Comment by axe312ger** [comment]
I wonder if we could prefix the ids after cleanup, as I got some SVGs from designers bloated with super long german ids created by illustrator :/

**Comment by axe312ger** [comment]
So I guess three solutions:

* make cleanUp ids configurable
* allow passing of whole SVGO config
* allow prefixing of cleaned up ids to still reduce file size but avoid id collisions

**Comment by xMokAx** [comment]
@axe312ger  I'm looking into `svgo` right now and will try to make the prefix unique to fix both my collision problem and your long ids problem and then will look into gatsby API to allow passing options.

**Comment by axe312ger** [comment]
Amazing! 😻

**Comment by axe312ger** [comment]
any progress here? 🙈

**Comment by xMokAx** [comment]
@axe312ger  Don't you remember that?
https://github.com/axe312ger/gatsby-transformer-inline-svg/pull/9

**Comment by axe312ger** [comment]
Looks like we forgot to close this one 🙈
